name: P-LifeSteal
version: '${project.version}'
main: eu.vibemc.lifesteal.Main
api-version: 1.18
authors: [ AUTHOR OF ORGIN CODE:devPrzemes GUIFIXXES:SAMJAKOB BUXFIXES&TESTING+GUITWEAKS:CODEMAN04]
description: Plugin for stealing lives.
softdepend:
  - PlaceholderAPI